version: '3.3'

services:
  pps:
    build:
      context: ./price_pulse_scraper/
      dockerfile: ./Dockerfile
    volumes:
      - data:/prise_pulse/price_pulse_scraper/price_pulse_scraper/data/gold

  db:
    build:
      context: ./price_pulse_mysql_db/
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: price_pulse
    volumes:
      - data:/docker-entrypoint-initdb.d/
    depends_on:
      - pps

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  data: